# TUTO Rototrans

We want to display the rototrans (aka homogeneous transform) of any segment from local coordinates to global coordinates such that any point P_in_local_segment can be transform in world's frame.

In our example, we will use the wu model.
When you load it, the model is in anatomical posture, in this example we will try to find the Rotranslation matrix between ulna and humerus when the elbow is bend.

---
### Formula

Let $ T_{world/segment} $ the homogeneous transform matrix between segment and world.

We have :

$ P_{world}= T_{world/segment} . P_{segment} $

If we want the rototrans matrix between two segment i and j, we need to pass by the world :

$ T_{i/j} = T_{i/ world} . T_{world/j} $

In order to get $ T_{i/ world}$, we inverse the matrix $ T_{world/i}$

Finally  :  $ P_{i}= T_{i/j} . P_{j} $

The position in i in relation to j is given by the rototranslation matrix between i and j, multiplied by the position in j.

___

In [27]:
import bioviz
import numpy as np
import biorbd

In [28]:
# Load the model
model_name = "models/wu_converted_definitif.bioMod"

biorbd_model = biorbd.Model(model_name)
np.set_printoptions(precision=10)

# Now the model is loaded as a biorbd object

Q is the vector that we get after manually placed the ulna into the animation and click on "copy to clipboard". It correspond to the values of our degrees of liberty.

In [44]:
# Q is supposed to be same dimension as biorbd_model.nbQ()

Q = np.array(
    [ 
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.1806,
        0.0
    ]
) 
# here is the Q when the elbow is bend (rotation of ulna by almost pi/2)

Now we have to find the numbers of our segment, ulna and humerus. Ulna is segment 30 ans Humerus is segment 23.

In [31]:
biorbd_model.GetBodyBiorbdId("humerus") # this function can be use to find a segment name

23

In [32]:
biorbd_model.GetBodyBiorbdId("ulna")

30

In [42]:
# So, we want to find the rototrans (aka homogeneous transform) of ulna and the humerus from local to global coordinates.

Rototrans_matrix_world_humerus = biorbd_model.globalJCS(Q, 23).to_array() # We converted the matrix into array in order to do matrice's operation thanks to numpy
Rototrans_matrix_world_ulna = biorbd_model.globalJCS(Q, 30).to_array() # globaJCS() return the joint coordinate system (JCS) for the segment in global reference frame at a given Q.
 

In order to get the rototrans matrix between world and segment, we use the fonction : globalJCS()

In [43]:
# We want to find the transformation matrix btw support and ulna
# Rototrans_matrix_ulna_support = Rototrans_matrix_ulna_world * Rototrans_matrix_world_support

# Rototrans_matrix_humerus_world is the inverse matrix of Rototrans_matrix_world_humerus, we use .transpose()
# .transpose() on the Rototrans object which actually inverses the rototranslation matrix.

Rototrans_matrix_humerus_world = biorbd_model.globalJCS(Q, 23).transpose().to_array()

# Be aware that Rototrans_matrix_world_ulna.transpose() would give the wrong matrix

# Finally
Rototrans_matrix_humerus_ulna = np.matmul(Rototrans_matrix_humerus_world, Rototrans_matrix_world_ulna)

print(Rototrans_matrix_humerus_ulna)

# We have Rototrans_matrix_humerus_ulna, so, we are now able to transform the coordinates of any point in the ulna
# frame to the humerus frame with the following formula:
# Position_in_humerus = Rototrans_matrix_humerus_ulna * Position_in_ulna


[[ 1.0000000000e+00  7.4499796266e-10 -1.8067501998e-09  6.5190604461e-03]
 [ 1.1288110620e-10  1.0000000037e+00  1.4822152464e-09 -3.1035003119e-01]
 [-1.7932619915e-09  7.1796937146e-10  9.9999999721e-01 -1.0605052325e-02]
 [ 0.0000000000e+00  0.0000000000e+00  0.0000000000e+00  1.0000000000e+00]]


## Do It Yourself 

Now that you saw an example, let's apply what you learn on an other example.

You must find the rototrans matrix between humerus and scapula in order to make an abduction of the arm to be parallel to transversal plan.  

In [37]:
import bioviz
import numpy as np
import biorbd

# Load the model
model_name = "models/wu_converted_definitif.bioMod"

biorbd_model = biorbd.Model(model_name)


# Now the model is loaded as a biorbd object

# Q is supposed to be same dimension as biorbd_model.nbQ()
# We give the Q

Q = np.array(
    [ 
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.6282,
        0.0,
        0.0,
        0.0

    ]
) 

# So, we want to find the rototrans (aka homogeneous transform) of humerus and the scapula from local to global coordinates.

In [39]:
biorbd_model.GetBodyBiorbdId("segment_name") # this function can be use to find a segment name

-1

In [41]:
# Uncomment and complete the following line 

# Rototrans_matrix_world_scapula = biorbd_model.globalJCS(Q, ...).to_array() # to complete, find the number which correspond to the scapula
# Rototrans_matrix_world_humerus = biorbd_model.globalJCS(Q, ...).to_array() # to complete, find the number which correspond to the humerus

# Rototrans_matrix_scapula_world = biorbd_model.globalJCS(Q, ...). ...().to_array() # to complete, find the right function to inverse matrix

# # Finally
# Rototrans_matrix_scapula_humerus = np.matmul(... , ... ) #put the right matrix in the matrix multiplication function

# print(Rototrans_matrix_scapula_humerus)
